language: ruby
rvm:
  - 1.8.7
  - 1.9.3
before_script:
after_script:
script: "bundle exec rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.6.9
  - PUPPET_VERSION=3.0.0
notifications:
  email: false
